name = "Forge Everything"
author = "Forge Everything Team"
version = "0.0.1-Alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bd86b5a0451895dc887c75a32bb29e3ad3ca505b54725897fdc8958fe69a00e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
